server:
  port: 8080



spring:
  datasource:
    url: jdbc:mariadb://svc.sel4.cloudtype.app:31245/Haso
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


    jackson:
      property-naming-strategy: SNAKE_CASE


  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql: DEBUG
#    com.zaxxer.hikari: DEBUG
#    org.springframework: DEBUG
#    org.springframework.web: DEBUG
#    org.example: DEBUG


jwt:
  accessExpire: 3600000
  refreshExpire: 259200000
  secret-key: ${JWT_SECRET}


file:
  dir: s3://courage.orangejuice-bucket/store



cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    s3:
      bucketName: courage.orangejuice-bucket
      region:
        staticRegion: ap-northeast-2
      stack:
        auto: false

